# Generated by Django 5.1.3 on 2024-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_pfp_alter_comment_id_alter_follower_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='network/header.jpg', null=True, upload_to='network/'),
        ),
    ]
